[build]
  publish = "dist"
  command = "pnpm install --no-frozen-lockfile && pnpm build"

[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_FLAGS = "--no-frozen-lockfile"
  PNPM_FLAGS = "--no-frozen-lockfile"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200